# Generated by Django 2.1.5 on 2019-10-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_insurancedata_format_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancedata',
            options={'verbose_name': 'Данные по СК'},
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
